### ISSUE TITLE
Generic kinematic chains support in MORSE is sub-optimal

### ISSUE THREAD

**Issue by severin-lemaignan** [morse-simulator/morse#382]
Despite large work done in #231, armatures (Blender name for kinematic chains) support in MORSE is sub-optimal.

This meta-bug tracks the issues and progresses made to improve it.

Amongst the open-issues:
- [x] <del>creating armatures remains tricky. [Doc could be improved](http://www.openrobots.org/morse/doc/latest/dev/armature_creation.html). -> cf [comment with updated doc below](https://github.com/laas/morse/issues/382#issuecomment-18937778)</del>
- [x] <del>Blender has also the concept of [Rigid Body Constraints](http://wiki.blender.org/index.php/Doc:2.6/Manual/Constraints/Relationship/Rigid_Body_Joint) that looks nicer to use, but it is not plugged with IK solvers.</del>
- [x] <del>Blender armatures [do not support 0-length joints](http://projects.blender.org/tracker/?func=detail&atid=498&aid=33172&group_id=9), which is an issue when several DoF have the same origin</del> -> can be workarounded by modeling a multi-DoF joint + adding constraint (`Limit rotation`) to the meshes when necessary, but...
- [ ] MORSE does not support multi-DoF joints
- [x] <del>Armatures do not support pure translation. They only have a concept of 'streching' that scales the bone (and hence the attached meshes)</del> -> can be workarounded by adding constraint (`Limit scaling`) to the mesh.
- [x] <del>Access the IK is not yet exposed in MORSE</del> Fixed in #460.
- [ ] Would be nice to be able to create an armature from a URDF file. Cf #547.
